fix: avoid undefined in totals DHIS2-14511
dhis2/analytics pull request #1552
Opened 2023-07-12 09:01 UTC by edoardo

Implements [DHIS2-14511](https://dhis2.atlassian.net/browse/DHIS2-14511)

---

### Key features

1. fix `undefined` in totals when value is 0 

---

### Description

The issue is well described in the ticket.
The problem in the code is that when the totals are computed, the value is not initialised to 0 when the input value is `undefined`.

---

### Screenshots

Before:
<img width="176" alt="Screenshot 2023-07-12 at 11 00 28" src="https://github.com/dhis2/analytics/assets/150978/a125d9ed-b51b-4ca7-8348-3ce9a5b02f50">

After:
<img width="166" alt="Screenshot 2023-07-12 at 11 00 17" src="https://github.com/dhis2/analytics/assets/150978/a5b7d969-be3a-4755-b5f6-9eb883cc07ae">

2023-07-12 09:17 UTC, martinkrulltott commented on src/modules/pivotTable/PivotTableEngine.js
> +                    if (!isNaN(value)) {
extract this check to a fn that can be tested by a unit test? (instead of repeating it 7 times)

2023-07-12 09:18 UTC, martinkrulltott reviewed
unit tests would be good, as these checks aren't that human readable

2023-08-17 12:32 UTC, edoardo commented
> unit tests would be good, as these checks aren't that human readable

Added unit tests for the new helper function.

2023-08-17 13:33 UTC, martinkrulltott requested changes
I would strongly suggest switching `processTotalValue` from an impure to a pure function, unless there are specific reasons not to

2023-08-17 13:57 UTC, edoardo commented
> I would strongly suggest switching `processTotalValue` from an impure to a pure function, unless there are specific reasons not to

Refactored.

2023-08-18 06:52 UTC, martinkrulltott commented on src/modules/pivotTable/__tests__/addToTotalIfNumber.js
> +        totalObj: { [field]: 100 },
is it necessary to use `totalObj` for the tests? Or could they just pass in e.g. `testName: 'foo', value: 1, total: 100, expected: 101`?

2023-08-18 07:18 UTC, martinkrulltott approved these changes

2023-08-18 07:25 UTC, merged